name: MasterDeployCI
on:
  push:
    branches:
      - publish-hw
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create Release Folder
      run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release
    - name: Switch to Release Folder
      run: |
        cd release
        ls -la
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.PRIVATE_HW_SECRET_TOKEN }}
        REPO_OWNER: matthewdhull
        VERBOSE: TRUE
        DEFAULT_BRANCH: publish-hw
        INITIAL_VERSION: 0.0.0
