name: Zip Files

on:
  push:
    branches:
      - publish-hw

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: hw1/ hw2/
          dest: hw-skeleton.zip
      - uses: actions/upload-artifact@v1
        with:
          name: hw-skeleton
          path: ${{ github.workspace }}/hw-skeleton.zip
